//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by ExportHTML.rc
//
#define IDR_EXPORTHTML                  101
#define IDD_HTML_EXPORT_OPTIONS         104
#define IDD_HTML_EXPORT_GENERAL_PAGE    105
#define IDD_HTML_EXPORT_APPEARANCE_PAGE 106
#define IDD_HTML_EXPORT_IMAGES_PAGE     107
#define IDD_HTML_EXPORT_NOTES_PAGE      108
#define IDS_ERROR_OPEN_FILE             102
#define IDS_ERROR_CREATE_DIRECTORY      103
#define IDI_MAINICON                    104
#define IDS_ERROR_WRITE_FILE            104
#define IDS_ERROR_WRITE_FILE2           105
#define IDS_WARNING_FILE_ALREADY_EXISTS 106
#define IDS_SAVE_FILE_FILTER            107
#define IDS_XML_PARSE_ERROR             108
#define IDS_AT_LINE_COLUMN              109
#define IDS_AT_S_S                      110
#define IDS_ERROR                       111
#define IDS_COM_ERROR                   112
#define IDS_TOOLTIP_TEMPLATE            113
#define IDS_TOOLTIP_BROWSE_TEMPLATE     114
#define IDS_TOOLTIP_DOCINFO             115
#define IDS_TOOLTIP_TOC_DEPTH           116
#define IDS_CUSTOM_SAVE_TEMPLATE_LABEL  117
#define IDS_CUSTOM_SAVE_INCLUDE_DESC    118
#define IDS_CUSTOM_SAVE_TOC_DEPTH       119
#define IDS_OPEN_TEMPLATE_FILTER        120
#define IDS_UNKNOWN_ERROR                121
#define IDS_CUSTOM_SAVE_CUSTOM_CSS       122
#define IDS_CUSTOM_SAVE_IMAGE_MAX_WIDTH  123
#define IDS_CUSTOM_SAVE_IMAGE_MAX_HEIGHT 124
#define IDS_ERROR_EMBEDDED_IMAGES_TEMPLATE 125
#define IDS_TOOLTIP_CUSTOM_CSS          126
#define IDS_TOOLTIP_BROWSE_CSS          127
#define IDS_TOOLTIP_IMAGE_MAX_WIDTH     128
#define IDS_TOOLTIP_IMAGE_MAX_HEIGHT    129
#define IDS_HTML_EXPORT_OPTIONS_TITLE   130
#define IDS_OPEN_CSS_FILTER             131
#define IDS_WARNING_EXTERNAL_RESOURCES   132
#define IDS_OPTIONS_TAB_GENERAL          133
#define IDS_OPTIONS_TAB_APPEARANCE       134
#define IDS_OPTIONS_TAB_IMAGES           135
#define IDS_OPTIONS_TAB_NOTES            136
#define IDS_OPTIONS_FORMAT               137
#define IDS_OPTIONS_ENCODING             138
#define IDS_OPTIONS_INCLUDE_TOC          139
#define IDS_OPTIONS_TEMPLATE             141
#define IDS_OPTIONS_STYLE                142
#define IDS_OPTIONS_FONT                 143
#define IDS_OPTIONS_CUSTOM_FONT          144
#define IDS_OPTIONS_FONT_SIZE            145
#define IDS_OPTIONS_LINE_HEIGHT          146
#define IDS_OPTIONS_CONTENT_WIDTH        147
#define IDS_OPTIONS_MARGINS              148
#define IDS_OPTIONS_TEXT_ALIGNMENT       149
#define IDS_OPTIONS_HEADING_ALIGNMENT    150
#define IDS_OPTIONS_CUSTOM_CSS           151
#define IDS_OPTIONS_CSS_CLEAR            152
#define IDS_OPTIONS_COVER_MODE           153
#define IDS_OPTIONS_IMAGES_FOLDER        154
#define IDS_OPTIONS_STANDALONE_WARNING   155
#define IDS_OPTIONS_NOTE_PLACEMENT       156
#define IDS_OPTIONS_INCLUDE_METADATA     157
#define IDS_OPTIONS_METADATA_ANNOTATION  158
#define IDS_OPTIONS_METADATA_TITLE       159
#define IDS_OPTIONS_METADATA_DOCUMENT    160
#define IDS_OPTIONS_METADATA_PUBLISH     161
#define IDS_OPTIONS_METADATA_HISTORY     162
#define IDS_OPTIONS_METADATA_AUTHORS     163
#define IDS_OPTIONS_METADATA_TRANSLATORS 164
#define IDS_OPTIONS_METADATA_CUSTOM      165
#define IDS_OPTIONS_VALUE_DEFAULT         166
#define IDS_OPTIONS_VALUE_CLASSIC         167
#define IDS_OPTIONS_VALUE_BOOK            168
#define IDS_OPTIONS_VALUE_MINIMAL         169
#define IDS_OPTIONS_VALUE_SERIF           170
#define IDS_OPTIONS_VALUE_SANS            171
#define IDS_OPTIONS_VALUE_SYSTEM          172
#define IDS_OPTIONS_VALUE_CUSTOM          173
#define IDS_OPTIONS_VALUE_LEFT            174
#define IDS_OPTIONS_VALUE_JUSTIFIED       175
#define IDS_OPTIONS_VALUE_CENTER          176
#define IDS_OPTIONS_VALUE_NORMAL          177
#define IDS_OPTIONS_VALUE_READING         178
#define IDS_OPTIONS_VALUE_VIEWPORT        179
#define IDS_OPTIONS_VALUE_AUTOMATIC       180
#define IDS_OPTIONS_VALUE_CUSTOM_NAME     181
#define IDS_OPTIONS_VALUE_SOURCE          182
#define IDS_OPTIONS_VALUE_BOOK_END        183
#define IDS_OPTIONS_VALUE_SECTION_END     184
#define IDS_OPTIONS_ERROR_TOC_DEPTH       185
#define IDS_OPTIONS_ERROR_IMAGE_SIZE      186
#define IDS_OPTIONS_ERROR_IMAGE_DIRECTORY 187
#define IDS_OPTIONS_ERROR_WARNING         188
#define IDS_OPTIONS_VALUE_LINE_120         189
#define IDS_OPTIONS_VALUE_LINE_150         190
#define IDS_OPTIONS_VALUE_NARROW           191
#define IDS_OPTIONS_VALUE_WIDE             192
#define IDS_OPTIONS_ERROR_FONT_SIZE        193
#define IDS_OPTIONS_ERROR_TEMPLATE         194
#define IDC_OPTIONS_TABS                 1014
#define IDC_INCLUDE_TOC                  1015
#define IDC_FORMAT_VALUE                 1017
#define IDC_ENCODING_VALUE               1018
#define IDC_STYLE                        1019
#define IDC_FONT_FAMILY                  1020
#define IDC_CUSTOM_FONT                  1021
#define IDC_FONT_SIZE                    1022
#define IDC_LINE_HEIGHT                  1023
#define IDC_CONTENT_WIDTH                1024
#define IDC_PAGE_MARGINS                 1025
#define IDC_TEXT_ALIGNMENT               1026
#define IDC_HEADING_ALIGNMENT            1027
#define IDC_CLEAR_CSS                    1028
#define IDC_COVER_MODE                   1029
#define IDC_IMAGES_FOLDER                1030
#define IDC_IMAGES_FOLDER_NAME           1031
#define IDC_STANDALONE_WARNING           1032
#define IDC_NOTE_PLACEMENT               1033
#define IDC_METADATA                     1034
#define IDC_METADATA_ANNOTATION          1035
#define IDC_METADATA_TITLE               1036
#define IDC_METADATA_DOCUMENT            1037
#define IDC_METADATA_PUBLISH             1038
#define IDC_METADATA_HISTORY             1039
#define IDC_METADATA_AUTHORS             1040
#define IDC_METADATA_TRANSLATORS         1041
#define IDC_METADATA_CUSTOM              1042
#define IDC_STYLE_LABEL                  1044
#define IDC_FONT_LABEL                   1045
#define IDC_FONT_SIZE_LABEL              1046
#define IDC_LINE_HEIGHT_LABEL            1047
#define IDC_CONTENT_WIDTH_LABEL          1048
#define IDC_MARGINS_LABEL                1049
#define IDC_TEXT_ALIGNMENT_LABEL         1050
#define IDC_HEADING_ALIGNMENT_LABEL      1051
#define IDC_COVER_MODE_LABEL             1052
#define IDC_IMAGES_FOLDER_LABEL          1053
#define IDC_IMAGES_FOLDER_NAME_LABEL     1054
#define IDC_STANDALONE_WARNING_LABEL     1055
#define IDC_NOTE_PLACEMENT_LABEL         1056
#define IDC_BROWSE                      1001
#define IDC_TEMPLATE                    1002
#define IDC_TOCDEPTH                    1004
#define IDC_TEMPLATE_LABEL              1005
#define IDC_TOC_DEPTH_LABEL             1006
#define IDC_CUSTOM_CSS                  1007
#define IDC_BROWSE_CSS                  1008
#define IDC_CUSTOM_CSS_LABEL            1009
#define IDC_IMAGE_MAX_WIDTH              1010
#define IDC_IMAGE_MAX_HEIGHT             1011
#define IDC_IMAGE_MAX_WIDTH_LABEL        1012
#define IDC_IMAGE_MAX_HEIGHT_LABEL       1013

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        107
#define _APS_NEXT_COMMAND_VALUE         40001
#define _APS_NEXT_CONTROL_VALUE         1005
#define _APS_NEXT_SYMED_VALUE           102
#endif
#endif
